DROP TABLE IF EXISTS vax, symptoms, vaers;

CREATE TABLE vax (
	VAERS_ID INT,
	VAX_TYPE VARCHAR,
	VAX_MANU TEXT,
	VAX_LOT VARCHAR,
	VAX_DOSE_SERIES VARCHAR,
	VAX_ROUTE VARCHAR,
	VAX_SITE VARCHAR,
	VAX_NAME TEXT
);

CREATE TABLE symptoms (
	VAERS_ID INT,
	SYMPTOM1 TEXT,
	SYMPTOMVERSION1	VARCHAR,
	SYMPTOM2 TEXT,
	SYMPTOMVERSION2	VARCHAR,
	SYMPTOM3 TEXT,
	SYMPTOMVERSION3	VARCHAR,
	SYMPTOM4 TEXT,
	SYMPTOMVERSION4	VARCHAR,
	SYMPTOM5 TEXT,
	SYMPTOMVERSION5 VARCHAR
);

CREATE TABLE vaers (
	VAERS_ID INT,
	RECVDATE DATE,
	STATED VARCHAR,
	AGE_YRS VARCHAR,
	CAGE_YR VARCHAR,
	CAGE_MO	VARCHAR,
	SEX VARCHAR,
	RPT_DATE DATE,
	SYMPTOM_TEXT TEXT,
	DIED VARCHAR,
	DATEDIED VARCHAR,
	L_THREAT VARCHAR,
	ER_VISIT VARCHAR,
	HOSPITAL VARCHAR,
	HOSPDAYS VARCHAR,
	X_STAY VARCHAR,
	DISABLED VARCHAR,
	RECOVD VARCHAR,
	VAX_DATE VARCHAR,
	ONSET_DATE VARCHAR,
	NUMDAYS VARCHAR,
	LAB_DATA VARCHAR,
	V_ADMINBY VARCHAR,
	V_FUNDBY VARCHAR,
	OTHER_MEDS TEXT,
	CUR_ILL VARCHAR,
	HISTORY VARCHAR,
	PRIOR_VAX VARCHAR,
	SPLTTYPE VARCHAR,
	FORM_VERS VARCHAR,
	TODAYS_DATE VARCHAR,
	BIRTH_DEFECT VARCHAR,
	OFC_VISIT VARCHAR,
	ER_ED_VISIT VARCHAR,
	ALLERGIES TEXT
);


